version: "3.7"

services:
  postgres:
    image: postgres:13.1
    ports:
      - 54322:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: kalle

  baikal:
    build: test/baikal
    ports:
      - 5232:80

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  nextcloud:
    build: test/nextcloud
    ports:
      - 6080:80
    environment:
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_AUTHTYPE: PLAIN
      MAIL_FROM_ADDRESS: nextcloud@localhost
