version: "3.7"

services:
  postgres:
    image: postgres:13.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: kalle

  baikal:
    image: ckulka/baikal:nginx
    ports:
      - 5232:80
    volumes:
      - ./test/baikal/Specific:/var/www/baikal/Specific
      - ./test/baikal/config:/var/www/baikal/config

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  nextcloud:
    build: test/nextcloud
    ports:
      - 6080:80
    environment:
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_AUTHTYPE: PLAIN
      MAIL_FROM_ADDRESS: nextcloud@localhost
