const tenant = "common"
export const client_id = process.env.MICROSOFTCLIENTID
export const redirect_uri = "http://localhost:3000/outlookRedirect"
export const response_mode = "query"
export const scope =  "offline_access user.read mail.read calendars.ReadWrite https://outlook.office.com/calendars.readwrite"
export const response_type = "code"
export const baseURL = "https://login.microsoftonline.com/" + tenant + "/oauth2/v2.0/"
export const grant_type_code = "authorization_code"
export const grant_type_refresh = "refresh_token"
export const client_secret = process.env.MICROSOFTCLIENTSECRET