# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [main]
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Fix file permissions for Baikal data
        run: sudo chmod -R 777 test/baikal/
      - run: npm ci
      - run: npm run lint
      - run: npm test -- --coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./.coverage/lcov.info
          flag-name: unit
          parallel: true
      - run: npm run build
        env:
          CALENDAR_PASSWORD_ENCRYPTION_PASSPHRASE: actionSecretWith32CharactersYoYo
          QUIRREL_BASE_URL: http://localhost:3000
          NODE_ENV: e2etest
      - name: Start services for E2E test
        run: docker-compose up -d
      - name: Wait for Postgres to startup
        run: sleep 5s
      - name: Migrate Database
        run: npx prisma migrate deploy --preview-feature
      - name: Seed Database
        run: npm run db:seed
      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          install: false
          record: true
          env: host=localhost,port=3000
          start: npx concurrently 'blitz start --production --port 3000' 'quirrel'
          wait-on: "http://localhost:3000"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SESSION_SECRET_KEY: supersecretsessionsecretkeywhichisatleast32byteslong
          QUIRREL_BASE_URL: http://localhost:3000
          SMTP_HOST: localhost
          SMTP_PORT: 1025
          SMTP_USER: ignored
          SMTP_PASSWORD: ignored
          EMAIL_FROM: local-dev@kalle.app
          MODE: test
          NODE_ENV: e2etest
      - name: Process Coverage Report
        run: npm run cypress:collect-coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
          flag-name: e2e
          parallel: true
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
