# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [main]
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Fix file permissions for Baikal data
        run: sudo chmod -R 777 test/baikal/
      - run: npm ci
      - run: npm run lint
      - run: npm test -- --coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./.coverage/lcov.info
      - run: npm run build
        env:
          CALENDAR_PASSWORD_ENCRYPTION_PASSPHRASE: actionSecretWith32CharactersYoYo
      - name: Start services for E2E test
        run: docker-compose up -d
      - name: Migrate Database
        run: npx prisma migrate deploy --preview-feature
      - name: Seed Database
        run: npm run db:seed
      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          install: false
          record: true
          env: host=localhost,port=3000
          start: npx blitz start --production --port 3000
          wait-on: "http://localhost:3000"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SESSION_SECRET_KEY: supersecretsessionsecretkeywhichisatleast32byteslong
